name = "cf-d1-blog-api"
compatibility_date = "2023-12-01"


# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "KV"
# id = ""

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "blog"
# database_id = ""

[placement]
mode = "smart"

# [vars]
# TOKEN_SECRET = "bronya"
# REFRESH_TOKEN_SECRET = "seele"
